#Connection Settings
driverClassName=oracle.jdbc.driver.OracleDriver
###  MDW Production Database
#url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521)))(CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=mdwdb) ))
#username=edbadm
#password=edbadm
### MDWTST Test Database
url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521))(CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=mdwtst) ))
username=EDBADM
password=EDBADM
# Number of initial connections created when connection pool starts (default is 0)
initialSize=1
# Maximum number of active connections that can be simultaneously connected in the pool
maxActive=20
# Maximum number of idle connections in the pool, excess idle connections will be released, negative means unlimited
maxIdle=10
# Minimum number of idle connections in the pool, new connections will be created if below this number
minIdle=5
# Maximum wait time in milliseconds when no available connection, pool waits for connection release
# Exception will be thrown if exceeding this time limit, -1 means infinite wait
# Unit: milliseconds, 1 minute
maxWait=60000
# Whether to print timeout error when automatically recycling timeout connections
logAbandoned=true 
# Whether to automatically recycle timeout connections
removeAbandoned=true  
# DBCP connection pool automatically manages connections used by application
removeAbandonedOnMaintenance=true
removeAbandonedOnBorrow=true
# Timeout recycle in seconds, 3 minutes
removeAbandonedTimeout=180
# driver default: specify transaction isolation level for connections created by the pool
# Available values: NONE, READ_UNCOMMITTED, READ_COMMITTED, REPEATABLE_READ
defaultTransactionIsolation=READ_COMMITTED
