#Connection Settings
driverClassName=oracle.jdbc.driver.OracleDriver
### MDWTST Test Database
#url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521))(CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=mdwtst) ))
#username=EDBADM
#password=EDBADM
###  MDW Production Database
url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521)))(CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=mdwdb) ))
username=EDBADM
password=edbadm
# Number of initial connections created when connection pool starts (default is 0)
initialSize=1
# Maximum number of active connections that can be simultaneously connected in the pool
maxActive=20
# Minimum number of idle connections in the pool, new connections will be created if below this number
minIdle=5
# Maximum wait time in milliseconds when no available connection, pool waits for connection release
# Exception will be thrown if exceeding this time limit, -1 means infinite wait
# Unit: milliseconds, 1 minute
maxWait=60000

# Configure how often to check for idle connections that need to be closed, unit: milliseconds
timeBetweenEvictionRunsMillis:60000
# Configure minimum survival time for a connection in the pool, unit: milliseconds
minEvictableIdleTimeMillis:300000
   
validationQuery:SELECT 1 FROM dual  
testWhileIdle:true  
testOnBorrow:false  
testOnReturn:false
# Enable PSCache and specify the size of PSCache on each connection
poolPreparedStatements:true  
maxOpenPreparedStatements:20

# Timeout in seconds. 180 seconds = 3 minutes
removeAbandonedTimeout=180
# Whether to recycle connections exceeding time limit
removeAbandoned=true
# Output error log when closing abandoned connections
logAbandoned=true
