#!-- Not required unless system cannot automatically detect
driverClassName=oracle.jdbc.driver.OracleDriver
### MDWTST Test Database
#jdbcUrl=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521))(CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=mdwtst) ))
#username=EDBADM
#password=EDBADM
###  MDW Production Database
jdbcUrl=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=XX.XX.XX.XX)(PORT=1521)))(CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=mdwdb) ))
username=edbadm
password=edbadm
#!-- Configure as true for read-only database to ensure safety
readOnly=false
#!-- Maximum duration to wait for connection pool to assign a connection (milliseconds), SQLException occurs if no available connection within this time, default: 30 seconds
connectionTimeout=60000
#!-- Maximum duration a connection can stay idle (milliseconds), released (retired) if timeout, default: 10 minutes
idleTimeout=600000
#!-- Connection lifetime (milliseconds), released (retired) if timeout and not used, default: 30 minutes, recommended to set 30 seconds less than database timeout, refer to MySQL wait_timeout parameter (show variables like '%timeout%';)
maxLifetime=1800000
#!-- Maximum number of connections allowed in the pool. Default: 10; Recommended formula: ((core_count * 2) + effective_spindle_count)
maximumPoolSize=20
minimumIdle=5

connectionTestQuery=SELECT 1 FROM dual
autoCommit=true
dataSource.cachePrepStmts=true
dataSource.prepStmtCacheSize=250
dataSource.prepStmtCacheSqlLimit=2048
dataSource.useServerPrepStmts=true
dataSource.useLocalSessionState=true
dataSource.useLocalTransactionState=true
dataSource.rewriteBatchedStatements=true
dataSource.cacheResultSetMetadata=true
dataSource.cacheServerConfiguration=true
dataSource.elideSetAutoCommits=true
dataSource.maintainTimeStats=false
