#连接设置
driverClassName=oracle.jdbc.driver.OracleDriver
### MDWTST 测试库
#url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.120.230.61)(PORT=1521))(CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=mdwtst) ))
#username=EDBADM
#password=EDBADM
###  MDW 正式库
url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.120.8.20)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=10.120.8.21)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=10.120.8.22)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=10.120.8.23)(PORT=1521)))(CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=mdwdb) ))
username=EDBADM
password=edbadm
# 连接池启动时创建的初始化连接数量（默认值为0）
initialSize=1
#连接池中可同时连接的最大的连接数
maxActive=20
#连接池中最小的空闲的连接数，低于这个数量会被创建新的连接
minIdle=5
#最大等待时间，无可用连接时，连接池等待连接释放的最大时间
#超过该时间限制会抛出异常，如果设置-1表示无限等待 
#以毫秒为单位 1分钟
maxWait=60000

#<!-- 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 -->
timeBetweenEvictionRunsMillis:60000
# <!-- 配置一个连接在池中最小生存的时间，单位是毫秒 -->
minEvictableIdleTimeMillis:300000
   
validationQuery:SELECT 1 FROM dual  
testWhileIdle:true  
testOnBorrow:false  
testOnReturn:false  
#<!-- 打开PSCache，并且指定每个连接上PSCache的大小 -->
poolPreparedStatements:true  
maxOpenPreparedStatements:20

# <!-- 超时时间；单位为秒。180秒=3分钟 -->  
removeAbandonedTimeout=180
# <!-- 超过时间限制是否回收 -->  
removeAbandoned=true
# <!-- 关闭abandoned连接时输出错误日志 -->
logAbandoned=true